=== sridharrajen89/Solutions_JEE1/1331/application.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	    targetNamespace="http://www.htc.org/application" 
	    xmlns="http://www.htc.org/application" 
	    elementFormDefault="qualified">

	<xsd:element name="application" type="ModulesType"/>
	
	<xsd:complexType name="ModulesType">
			<xsd:sequence>
				<xsd:element name="module" type="ModuleType" maxOccurs="unbounded"/>
			</xsd:sequence>
	</xsd:complexType>
	
	
	<xsd:complexType name="ModuleType">
		<xsd:sequence>
			<xsd:element name="menuitem1" type="xsd:string"/>
			<xsd:element name="menuitem2" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:ID" use="required"/>
	</xsd:complexType>	
	
</xsd:schema>

=== sridharrajen89/Solutions_JEE1/1331/application.xml
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                                                                                              

<application xmlns="http://www.htc.org/application" 
       xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" 
       ns:schemaLocation="http://www.htc.org/application application.xsd">

	<module name='Purchases'>
			<menuitem1>Purchase Order</menuitem1>
			<menuitem2>Purchase Returns</menuitem2>
	</module>
	
	
	<module name='Sales'>
			<menuitem1>Sales Order</menuitem1>
			<menuitem2>Sales Returns</menuitem2>
	</module>
	
	<module name='Finance'>
			<menuitem1>Payments</menuitem1>
			<menuitem2>Receivables</menuitem2>
	</module>
    
</application>
