=== sridharrajen89/Solutions_JEE1/1331/trains.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	    targetNamespace="http://www.htc.org/train" 
	    xmlns="http://www.htc.org/train" 
	    elementFormDefault="qualified">

	<xsd:element name="trains" type="TrainsType"/>
	
	<xsd:complexType name="TrainsType">
			<xsd:sequence>
				<xsd:element name="train" type="trainType" maxOccurs="unbounded"/>
			</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="trainType">
			<xsd:sequence>
				<xsd:element name="train-name" type="xsd:string" maxOccurs="1"/>
				<xsd:element name="from" type="xsd:string" maxOccurs="1"/>
				<xsd:element name="to"   type="xsd:string" maxOccurs="1"/>
				<xsd:element name="journey-info" type="journeyType" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="no" type="xsd:ID" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="journeyType">
			<xsd:sequence>
				<xsd:element name="station" type="stationType" maxOccurs="unbounded" />
			</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="stationType">
			<xsd:sequence>
				<xsd:element name="name"         type="xsd:string" />
				<xsd:element name="arrival-time" type="xsd:string"/>
				<xsd:element name="depature-time" type="xsd:string" />
			</xsd:sequence>
			<xsd:attribute name="num" type="xsd:ID" use="required"/>
	</xsd:complexType>
	
</xsd:schema>

=== sridharrajen89/Solutions_JEE1/2250/AdvExercises/Ex5/Trains.xml
<?xml version="1.0" encoding="UTF-8"?>
<trains xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Trains.xsd">
  <train no="TR12760">
    <train-name>Chennai Express</train-name>
    <from>from</from>
    <to>to</to>
    <journey-info>
      <station no="1">
        <name>name</name>
        <arrival-time>arrival-time</arrival-time>
        <departure-time>departure-time</departure-time>
      </station>
    </journey-info>
  </train>
</trains>

=== sridharrajen89/Solutions_JEE1/2250/AdvExercises/Ex 4/Trains1.xml
<?xml version="1.0" encoding="UTF-8"?>
<trains xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Trains.xsd">
  <train no="">
    <train-name>train-name</train-name>
    <from>from</from>
    <to>to</to>
    <journey-info>
      <station no="">
        <name>name</name>
        <arrival-time>arrival-time</arrival-time>
        <departure-time>departure-time</departure-time>
      </station>
    </journey-info>
  </train>
</trains>

=== sridharrajen89/Solutions_JEE1/1331/trains.xml
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                                                                                              

<trains xmlns="http://www.htc.org/train" 
       xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" 
       ns:schemaLocation="http://www.htc.org/train trains.xsd">

	<train no="TR12760">
			<train-name>Chennai Express</train-name>
			<from> Chennai </from>
			<to> Hyderabad </to>
			<journey-info>
					<station num="T1">
						<name>Tirupathi</name>
						<arrival-time>6pm</arrival-time>
						<depature-time>9pm</depature-time>
					</station>
			</journey-info>
	</train>	
	
	<train no="TR12761">
			<train-name>HydExpress</train-name>
			<from> Hyderabad </from>
			<to> Delhi </to>
			<journey-info>
					<station num="T2">
						<name>Renugnta</name>
						<arrival-time>7pm</arrival-time>
						<depature-time>9pm</depature-time>
					</station>
			</journey-info>
	</train>							

    <train no="TR12578">
        <train-name>Goutami</train-name>
        <from>Kakinada</from>
        <to>Hyderabad</to>
        <journey-info>
            <station num="T3">
                <name>Vijayawada</name>
                <arrival-time>11am</arrival-time>
                <depature-time>12pm</depature-time>
            </station>
            <station num="T4">
                <name>Annavaram</name>
                <arrival-time>12am</arrival-time>
                <depature-time>1pm</depature-time>
            </station>
        </journey-info>
    </train>
</trains>
